# Generated by Django 6.0.4 on 2026-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sentiment',
            field=models.CharField(blank=True, help_text='AI Sentiment Analysis', max_length=50, null=True),
        ),
    ]
